### ISSUE TITLE
Speed

### ISSUE THREAD

**Issue by hugbubby** [midonet/tssrp6a#83] opened 2021-06-27 05:44 UTC
Our users are complaining about 1-2 minutes login wait times on mobile. Is this something that can be improved?

**Comment by bufistov** [comment] 2021-06-27 22:00
Hi @hugbubby! [This test](https://github.com/midonet/tssrp6a/blob/e8fd29627d3c84255d1e47191afd7f96634992e7/test/session.test.ts#L37) runs 20 signup/signin's. The unit test step takes [9s on GitHub runner.](https://github.com/midonet/tssrp6a/runs/2809346335?check_suite_focus=true).

Can it be that delay is caused by high network latency?

**Comment by bufistov** [comment] 2021-09-02 15:15
Closing for now, please re-open if the issue still persist.

**Closed by bufistov** 2021-09-02 15:15 UTC
